version: 2
jobs:
  build:
    docker:
      - image: circleci/rust

    steps:
      - checkout

      - run:
          name: format
          command: cargo fmt --all -- --check

      - run:
          name: lint
          command: |
            rustup component add clippy
            cargo clippy --all-features -- -D warnings

      - run:
          name: test
          command: cargo test