version: 2
jobs:
  build:
    docker:
      - image: circleci/rust

    steps:
      - checkout

      - run:
          name: format
          command: cargo fmt

      - run:
          name: lint
          command: rustup component add clippy && cargo clippy

      - run:
          name: test
          command: cargo test